const ORDER_STATUS = {
  PENDING: 'PENDING',
  TAKE: 'TAKE',
  CALL_AGAIN: 'CALL_AGAIN',
  CONFIRMED: 'CONFIRMED',
  SHIPPED: 'SHIPPED',
  RETURNED: 'RETURNED',
  PAID: 'PAID',
  TRASHED: 'TRASHED',
  CANCELLED: 'CANCELLED',
}

export default ORDER_STATUS
