# Generated by Django 5.2.4 on 2025-07-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        help_text="Upload an XLSX or CSV file containing order data.",
                        upload_to="order_imports/",
                        verbose_name="Order Import File",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
