# Generated by Django 5.2.4 on 2025-07-25 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_imports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderimport",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="The agent to which this order import is assigned.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_imports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent",
            ),
        ),
    ]
