# Generated by Django 5.1.4 on 2025-01-31 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_agent_order_assigned_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="assigned_user",
            new_name="agent",
        ),
    ]
