# Generated by Django 5.1.4 on 2025-01-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_assigned_user_order_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("TAKE", "Take"),
                    ("CALL_AGAIN", "Call Again"),
                    ("CONFIRMED", "Confirmed"),
                    ("SHIPPED", "Shipped"),
                    ("RETURNED", "Returned"),
                    ("PAID", "Paid"),
                    ("TRASHED", "Trashed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
    ]
