# Generated by Django 5.1.4 on 2025-02-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_customer_customercomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
