# Generated by Django 5.2.4 on 2025-07-25 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_imports", "0001_initial"),
        ("orders", "0007_customercomment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_import",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="order_imports.orderimport",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("IMPORTED", "Imported")],
                default="NORMAL",
                max_length=255,
            ),
        ),
    ]
