# Generated by Django 5.2.4 on 2025-07-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_imports", "0001_initial"),
        ("orders", "0010_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_import",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="order_imports.orderimport",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_item",
                to="orders.order",
            ),
        ),
    ]
