# Generated by Django 5.1.4 on 2025-01-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
