# Generated by Django 5.1.4 on 2025-01-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpage",
            name="template_path",
            field=models.FilePathField(
                default="", path="templates/product_pages", recursive=True
            ),
            preserve_default=False,
        ),
    ]
