# Generated by Django 5.1.4 on 2025-01-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productpage_template_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
