# Generated by Django 5.1.4 on 2025-01-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpage",
            name="template_path",
            field=models.FilePathField(path="templates/product-pages/", recursive=True),
        ),
    ]
